version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    ports:
      - 3000:3000
    container_name: express-container
